module.exports = {
  lessons: [{ type: "autogenerated", dirName: "lessons" }],
  progress: [{ type: "autogenerated", dirName: "progress" }],
  assignment: [{ type: "autogenerated", dirName: "assignment" }],
}
