module.exports = {
    lessons: [{type: 'autogenerated', dirName: 'lessons'}],
    conferences: [{type: 'autogenerated', dirName: 'conferences'}],
    students: [{type: 'autogenerated', dirName: 'students'}],
    assignment: [{type: 'autogenerated', dirName: 'assignment'}],
}