module.exports = {
    lessons: [{type: 'autogenerated', dirName: 'lessons'}],
    conferences: [{type: 'autogenerated', dirName: 'conferences'}],
    skills: [{type: 'autogenerated', dirName: 'skills'}],
}